import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";

const SoraSans = Sora({
  variable: "--font-Sora-sans",
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by My Portfolio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable} ${SoraSans.className} antialiased`}>{children}</body> */}
      <body className={` ${SoraSans.className} antialiased`}>{children}</body>
    </html>
  );
}
