import type { Metadata } from "next";
import { Sora } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider/theme-provider";

const sora = Sora({
  subsets: ["latin"],
  variable: "--font-sora-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by My Portfolio",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${sora.className} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
